admins: []
servers: []
shared_token: "sm_change_me_or_generate_with_command"
page_size: 8
offline_timeout: 30
public_status: true
include_local: true
alert:
  enabled: true
  cooldown: 120
render:
  imgType: png
show_ip_in_image: false
